#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#commonLabels:   #Selector and labels and selector re updated by default (risky) may affect selector function 
#   version: lec-16 

#commonAnnotations:
#  annotated-by: kustomize

#namePrefix: lec-16-

#resources:
#- mysql
#- ../base


#  V1 This is done using labels field, it update labels only (selectors template are optional )

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels: 
- pairs:
    version: lec-16
  includeSelectors: false    #for selectors  
  includeTemplates: false    # for templates 

#Note: after this you will still see lec-16 : thats beacuse base had common labels turn on 
#Advisable not to set this in base 

commonAnnotations:
  annotated-by: kustomize

namePrefix: lec-16-

resources:
- mysql
- ../base