apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:         # Main difference between secret and config generattor 
  - name: mysql-secret
    envs:
      - mysql-secret.properties

#This only genrates opaque type of secret (base 64 enocded)

generatorOptions:
  disableNameSuffixHash: true
  labels:
    generated: "true"

resources:
- deployment.yml
- service.yml