#=========================================================

# V3: Demonstrate how to use strategic merge conviennece field  
#tis version uses the patch limit.yml files to do the patching  

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    version: lec-18
  includeTemplates: true


namePrefix: lec-18-
namespace: lec-18

patchesStrategicMerge:
  - patches/patch-limits.yml 

resources:
- mysql
- ../base
- namespace.yml



#=========================================================

# V2: Remove unnecessary meta data on target, 
# In the most basic level. you only need kind and name to indentify  

#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#labels:
#- pairs:
#    version: lec-18
#  includeTemplates: true


#namePrefix: lec-18-
#namespace: lec-18

#patches:
#- path: patches/patch-limits.yml # patch file
#  target:   #Set of metadata used by kustomised to find the resource 
#    kind: Deployment
#    name: mysql
 

#resources:
#- mysql
#- ../base
#- namespace.yml


#===============================================
# V1 :Basic patch, file in patches/patch-limit.yml , updating mysql deplyoment
#Patching is usually the last rsort as it will protentially mkes ur yml file hard to managed/  

#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#labels:
#- pairs:
#    version: lec-18
#  includeTemplates: true


#namePrefix: lec-18-
#namespace: lec-18

#patches:
#- path: patches/patch-limits.yml # patch file
#  target:   #Set of metadata used by kustomised to find the resource 
#    group: apps   #group and rversions are seen in kubectl api-resources , api version contains [group/version]
#    version: v1
#    kind: Deployment
#    name: mysql
#    labelSelector: "app=mysql"
#    annotationSelector: "annotated-by=kustomize"

# NOTE: If you choose incorrect metadata (wrong group or type) kustomise will just ignore, no patchng done 

#resources:
#- mysql
#- ../base
#- namespace.yml

#====================================

#patchesStrategicMerge:
#  - patches/patch-limits.yml

# patches:
# - path: patches/patch-limits.yml # patch file
#   target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: mysql
#     labelSelector: "app=mysql"
#     annotationSelector: "annotated-by=kustomize"

# - patch: |- #inline patching
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: mysql 
#     spec:
#       template:
#         spec:
#           containers:
#             - name: mysql
#               resources:
#                 requests:
#                   memory: "100Mi"
#                   cpu: "100m"
#                 limits:
#                   memory: "150Mi"
#                   cpu: "150m"
#   target:
#       group: apps
#       version: v1
#       kind: Deployment
#       name: mysql
#       labelSelector: "app=mysql"
#       annotationSelector: "annotated-by=kustomize"

