#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#commonLabels:
#  version: lec-15

#namePrefix: lec-15-

#namespace: lec-15   #This will use the name space for all object, and overwrite any namespace field if different 



#resources:
#- mysql      #Folder 
#- ../base    #Follder 
#- namespace.yml   #namespace is already defined in this file, without it if ns not created will have error 


#iN THIS VERSION WE use a transformer files  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: lec-15

namePrefix: lec-15-

transformers:  #This can prevent namespace that are dfefined from being overwritten 
   - ./transformers/namespace.yml

resources:
- mysql
- ../base
- namespace.yml   #namespace is already defined in this file, without it if ns not created will have error 