apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: lec-15

namePrefix: lec-15-

namespace: lec-15   #This will use the name space 

# transformers:
#   - ./transformers/namespace.yml

resources:
- mysql
- ../base
#- namespace.yml   #namespace is already defined in this file, without it if ns not created will have error 