
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: v1

namePrefix: v1- 

resources:
- ../base

#this is the final one that the lecture left with 



#----------------------V3 --------------------------------------

#This is V3 way of doing (most moden, just put namePrefox: )
#these remove the needs to even have a transformer folder or to right the transformer cod ein 
#This add to metadata for every main items (IE deployment, service )

#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#commonLabels:
  version: v1

#namePrefix: v1-convenience-   #Renamed 
#nameSuffix: -transformers     #Suffix append at back 

#resources:
#- ../base





#----------------------V2 --------------------------------------
#V2 way to write transformer/name-prefix directly into the kustomzed file   

#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#commonLabels:     # Convneience field with a pre-built transformation function 
#  version: v1

#resources:
#- ../base   # use base folder 

#transformers:
#- |-
#  apiVersion: builtin
#  kind: PrefixSuffixTransformer
#  metadata:
#    name: my-prefix-transformer
#  prefix: v1-inline-    
#  # suffix: -transformers  #Suffix will attached ot the back  
#  fieldSpecs:   #Field to be affected is metadata/name "if base = app-pod" end reuslt is v1-app--pod 
#  - path: metadata/name


#Note indentation is critical for this to work. its quite a hassle and now not commonly used 


#----------------------V1 --------------------------------------
#V1 : Uses ./transformers/name-prefix 
    # label.yml = eg of label transformer 
    # name-prefix.yml  = eg of preffix sufix tarnsfor,er 
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#commonLabels:     # Convneience field with a prebuilt transformation function 
#  version: v1

#resources:
#- ../base   # use base folder 

#transformers:    #to use transformers you need to link from kustomized 
#- ./transformers/name-prefix.yml   #this links to a file 