apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: v1


#This is V3 way of doing (most moden, just put namePrefox: )
#these remove the needs to even have a transformer folder or to right the transformer cod ein 
#This add to metadata for every main items (IE deployment, service )

namePrefix: v1-
#namePrefix: v1-convenience-   #Renamed 


resources:
- ../base

#V2 way to write transformers thi sis v1-inline-    . This way us not giving way to convience filed
#t#ransformers: 
#- |-
#  apiVersion: builtin
#  kind: PrefixSuffixTransformer
#  metadata:
#    name: my-prefix-transformer
#  prefix: v1-inline-    
#  # suffix: -transformers  #orefux
#  fieldSpecs:   #Field to be affected is metadata/name "if base = app-pod" end reuslt is v1-app--pod 
#  - path: metadata/name



#V1 way to write transformers 
# transformers:    #to use transformers you need to link from kustomized 
# - ./transformers/name-prefix   #this links to a file 