#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#commonLabels:
#  version: v1

#namePrefix: v1-

#resources:
#- ../base

#This is V3 way of doing (most moden, just put namePrefox: )
#these remove the needs to even have a transformer folder or to right the transformer cod ein 
#This add to metadata for every main items (IE deployment, service )



#namePrefix: v1-convenience-   #Renamed 
#nameSuffix: -transformers #Suffic append at back 




#V2 way to write transformers thi sis v1-inline-    . This way us not giving way to convience filed
#t#ransformers: 
#- |-
#  apiVersion: builtin
#  kind: PrefixSuffixTransformer
#  metadata:
#    name: my-prefix-transformer
#  prefix: v1-inline-    
#  # suffix: -transformers  #orefux
#  fieldSpecs:   #Field to be affected is metadata/name "if base = app-pod" end reuslt is v1-app--pod 
#  - path: metadata/name





#V1 : Uses ./transformers/name-prefix 
    # label.yml = eg of label transformer 
    # name-prefix.yml  = eg of preffix sufix tarnsfor,er 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:     # Convneience field with a prebuilt transformation function 
  version: v1

resources:
- ../base   # use base folder 

transformers:    #to use transformers you need to link from kustomized 
- ./transformers/name-prefix.yml   #this links to a file 