#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#configMapGenerator:
#  - name: mysql-config
#    envs:
#      - mysql-config.properties

#generatorOptions:
#  disableNameSuffixHash: true
#  labels:
#    generated: "true"

#resources:
#- deployment.yml
#- service.yml



################### First version of file intial 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: mysql-config
    envs:
      - mysql-config.properties

resources:
- deployment.yml
- service.yml

#This version generate a config map that had a randm 